[
  { "Num": "01", "Wilaya": "Adrar" },
  { "Num": "02", "Wilaya": "Chlef" },
  { "Num": "03", "Wilaya": "Laghouat" },
  { "Num": "04", "Wilaya": "Oum El Bouaghi" },
  { "Num": "05", "Wilaya": "Batna" },
  { "Num": "06", "Wilaya": "Béjaïa" },
  { "Num": "07", "Wilaya": "Biskra" },
  { "Num": "08", "Wilaya": "Béchar" },
  { "Num": "09", "Wilaya": "Blida" },
  { "Num": "10", "Wilaya": "Bouira" },
  { "Num": "11", "Wilaya": "Tamanrasset" },
  { "Num": "12", "Wilaya": "Tébessa" },
  { "Num": "13", "Wilaya": "Tlemcen" },
  { "Num": "14", "Wilaya": "Tiaret" },
  { "Num": "15", "Wilaya": "Tizi Ouzou" },
  { "Num": "16", "Wilaya": "Alger" },
  { "Num": "17", "Wilaya": "Djelfa" },
  { "Num": "18", "Wilaya": "Jijel" },
  { "Num": "19", "Wilaya": "Sétif" },
  { "Num": "20", "Wilaya": "Saïda" },
  { "Num": "21", "Wilaya": "Skikda" },
  { "Num": "22", "Wilaya": "Sidi Bel Abbès" },
  { "Num": "23", "Wilaya": "Annaba" },
  { "Num": "24", "Wilaya": "Guelma" },
  { "Num": "25", "Wilaya": "Constantine" },
  { "Num": "26", "Wilaya": "Médéa" },
  { "Num": "27", "Wilaya": "Mostaganem" },
  { "Num": "28", "Wilaya": "M'Sila" },
  { "Num": "29", "Wilaya": "Mascara" },
  { "Num": "30", "Wilaya": "Ouargla" },
  { "Num": "31", "Wilaya": "Oran" },
  { "Num": "32", "Wilaya": "El Bayadh" },
  { "Num": "33", "Wilaya": "Illizi" },
  { "Num": "34", "Wilaya": "Bordj Bou Arréridj" },
  { "Num": "35", "Wilaya": "Boumerdès" },
  { "Num": "36", "Wilaya": "El Tarf" },
  { "Num": "37", "Wilaya": "Tindouf" },
  { "Num": "38", "Wilaya": "Tissemsilt" },
  { "Num": "39", "Wilaya": "El Oued" },
  { "Num": "40", "Wilaya": "Khenchela" },
  { "Num": "41", "Wilaya": "Souk Ahras" },
  { "Num": "42", "Wilaya": "Tipaza" },
  { "Num": "43", "Wilaya": "Mila" },
  { "Num": "44", "Wilaya": "Aïn Defla" },
  { "Num": "45", "Wilaya": "Naâma" },
  { "Num": "46", "Wilaya": "Aïn Témouchent" },
  { "Num": "47", "Wilaya": "Ghardaïa" },
  { "Num": "48", "Wilaya": "Relizane" },
  { "Num": "49", "Wilaya": "Timimoun" },
  { "Num": "50", "Wilaya": "Bordj Badji Mokhtar" },
  { "Num": "51", "Wilaya": "Ouled Djellal" },
  { "Num": "52", "Wilaya": "Béni Abbès" },
  { "Num": "53", "Wilaya": "In Salah" },
  { "Num": "54", "Wilaya": "In Guezzam" },
  { "Num": "55", "Wilaya": "Touggourt" },
  { "Num": "56", "Wilaya": "Djanet" },
  { "Num": "57", "Wilaya": "El M'Ghair" },
  { "Num": "58", "Wilaya": "El Menia" }
]
